### ISSUE TITLE
Where can I find gdrivedownload.py?

### ISSUE THREAD

**Issue by ghost** [mahavird/my_deep_anpr#6]
I wanted to directly see the results of some images. It says that you can download the weights.npz by this command but it needs the gdrivedownload.py file.

python gdrivedownload.py 1ZArKaR2HfY_319A7WUAVRSU7KO8E5klE /home/mahavircingular/my_deep_anpr/weights.npz

**Comment by pkmantra** [comment]
me too looking for gdrivedownload.py

please help

**Comment by ghost** [comment]
> me too looking for gdrivedownload.py
> 
> please help

I googled how to download gdrive file with file ID
maybe this will help - https://stackoverflow.com/questions/15057907/how-to-get-the-file-id-so-i-can-perform-a-download-of-a-file-from-google-drive-a
Or you can google it for the solutions.

**Comment by AshwinRaikar88** [comment]
Download the weights file from here 
https://drive.google.com/u/1/uc?export=download&confirm=bFo1&id=1ZArKaR2HfY_319A7WUAVRSU7KO8E5klE

Enjoy 🎉
